import {maxPrice} from './index_hw1.js';
import {getSumOfNumbers} from './index_hw2.js';
import {getRandomNumber} from './index_hw3.js';
import {marksStudents} from './index_hw4.js';
import {replaceBadWords} from './index_hw5.js';
import {calculateWordLetters} from './index_hw6.js';
import {ukraine, getMySalary} from './index_hw7.js';
import {student} from './index_hw8.js';
import {generateBlocks, generateBlocksInterval} from './index_hw10.js';
import {getRandomChinese} from './index_hw12.js';
import {idGenerator} from './index_hw15.js';
import './styles.css';
console.log("Max price from HW#1:", maxPrice);
getSumOfNumbers();
console.log("Random number from HW#3:", getRandomNumber(1, 9));
console.log("Students with marks from HW#4:", marksStudents);
console.log("Replace bad word from HW#5:", replaceBadWords("Are you fucking kidding?"));
console.log("Calculate word letters from HW#6:", calculateWordLetters("Test"));
getMySalary(ukraine);
console.log("Get info about student from HW#8:", student.getInfo());
generateBlocks();
generateBlocksInterval();
getRandomChinese(4);
console.log("Id Generator from HW#15:", idGenerator.next().value);
console.log("Id Generator from HW#15:", idGenerator.next().value);
console.log("Id Generator from HW#15:", idGenerator.next().value);